name: "GMC 3xx Radiation Monitor"
description: "Radiation Monitor Sensor Interface"
version: "2026.01.14.n"
slug: "gmc3xx_monitor_nd"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  port: "/dev/ttyUSB1"
  baudrate: 115200
  mqtt_server: "localhost"
  mqtt_port: 1883
  mqtt_user: "user"
  mqtt_password: "password"
  repeat: "60"
schema:
  port: str
  baudrate: int
  mqtt_server: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  repeat: int
init: false
startup: once
uart: true
host_network: true
video: false
